### ISSUE TITLE
not plotting sensor 0 values correctly

### ISSUE THREAD

**Issue by christakahashi** [autosportlabs/Podium-App-features-and-issues#6]
### Issue:  
podium.live webpage throws out 0's in sensor data and connects the remaining data points with lines.  

### to reproduce: 
see brakepress plot here: https://podium.live/events/ldrl-2021-06-05-pacific-6hr/device/apexoffailure-800-silver-rx8-ls?laps[]=21

which generates this plot:
![image](https://user-images.githubusercontent.com/1870494/121272465-e47e9b80-c87a-11eb-9d22-664713664ce9.png)
the data from podium.live looks like this:
![image](https://user-images.githubusercontent.com/1870494/121272491-f6603e80-c87a-11eb-8eae-a1789da2a650.png)
and that same data when i remove all the 0 data points looks like the first image:
![image](https://user-images.githubusercontent.com/1870494/121272516-037d2d80-c87b-11eb-868b-81b65edeac8d.png)

**Comment by brentpicasso** [comment]
Hi, thanks for the note and report. 

it looks like it renders correctly in the Podium app; try using that to review your data - there are also more powerful analysis capabilities as well.  We will eventually be deprecating the web interface after the podum app is in production. http://podium.live/software

![image](https://user-images.githubusercontent.com/3267533/121284872-58786e00-c892-11eb-9f44-64dc70dd3e6f.png)
